exclude: ["README.md"]


# Site settings
title: PiSensors
tag_text: PiSensors
email: ouyang@cs.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pisensors" # the subpath of your site, e.g. /blog/
url: "http://tylerwowen.github.io" # the base hostname & protocol for your site
github_username:  tylerwowen


# Build settings
markdown: kramdown
kramdown:
  input: GFM
